language: python
python:
- 2.7
before_install:
- openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in id_rsa.enc -out id_rsa -d
install:
- chmod 600 id_rsa
- eval `ssh-agent -s`
- ssh-add id_rsa
- ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@104.236.155.138
- mkdir i-logged-on
- cd i-logged-on
- echo Great success!
- exit
script:
- echo done.
